enum EntitiesActionTypes {
  ADD_ENTITY = "ADD_ENTITY",
  UPDATE_ENTITY = "UPDATE_ENTITY",
  DELETE_ENTITY = "DELETE_ENTITY",
  RESET_ENTITIES = "RESET_ENTITIES",
  SET_ACTIVE_ID = "ADD_ACTIVE_ID",
  RESET_ACTIVE_ID = "RESET_ACTIVE_ID"
};

export default EntitiesActionTypes;
